# Generated by Django 3.2.5 on 2021-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactSavvyApi', '0002_contact_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
