# Generated by Django 3.2.5 on 2021-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactSavvyApi', '0003_alter_contact_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='John', max_length=60),
        ),
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(default='Doe', max_length=60),
        ),
    ]
